import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin-ext"], variable: "--font-inter" });
const dm_sans = DM_Sans({ subsets: ["latin-ext"], variable: "--font-dm-sans" });

const fonts = [inter.className, dm_sans.className].join(" ");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};
const LayoutRoot = (props: Props) => {
  const { children } = props;
  return (
    <html lang="en">
      <body className={fonts}>{children}</body>
    </html>
  );
};

export default LayoutRoot;
