import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin-ext"] });
const dm_sans = DM_Sans({ subsets: ["latin-ext"] });

const fonts = [inter, dm_sans];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};
const LayoutRoot = (props: Props) => {
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default LayoutRoot;
